// PowerSync Configuration for Offline-First CRM
// Mobile app uses this to sync Supabase data locally

export const powersyncConfig = {
  databaseName: "nexus_crm.db",
  schema: {
    users: `
      CREATE TABLE users (
        id TEXT PRIMARY KEY,
        email TEXT NOT NULL,
        full_name TEXT,
        avatar_url TEXT,
        role TEXT NOT NULL,
        manager_id TEXT,
        phone TEXT,
        department TEXT,
        is_active INTEGER DEFAULT 1,
        last_login_at TEXT,
        created_at TEXT,
        updated_at TEXT
      )
    `,
    leads: `
      CREATE TABLE leads (
        id TEXT PRIMARY KEY,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        mobile TEXT,
        company TEXT,
        job_title TEXT,
        status TEXT NOT NULL,
        source TEXT NOT NULL,
        score INTEGER DEFAULT 0,
        owner_id TEXT NOT NULL,
        team_id TEXT,
        address TEXT,
        tags TEXT,
        custom_fields TEXT,
        notes TEXT,
        converted_at TEXT,
        converted_contact_id TEXT,
        converted_opportunity_id TEXT,
        zoho_lead_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    contacts: `
      CREATE TABLE contacts (
        id TEXT PRIMARY KEY,
        account_id TEXT,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        mobile TEXT,
        job_title TEXT,
        department TEXT,
        owner_id TEXT NOT NULL,
        team_id TEXT,
        address TEXT,
        tags TEXT,
        custom_fields TEXT,
        notes TEXT,
        zoho_contact_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    accounts: `
      CREATE TABLE accounts (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        industry TEXT,
        website TEXT,
        owner_id TEXT NOT NULL,
        team_id TEXT,
        tags TEXT,
        custom_fields TEXT,
        notes TEXT,
        zoho_contact_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    opportunities: `
      CREATE TABLE opportunities (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        account_id TEXT,
        contact_id TEXT,
        lead_id TEXT,
        stage TEXT NOT NULL,
        probability INTEGER DEFAULT 10,
        amount REAL NOT NULL DEFAULT 0,
        currency TEXT DEFAULT 'AED',
        expected_close_date TEXT,
        actual_close_date TEXT,
        owner_id TEXT NOT NULL,
        team_id TEXT,
        description TEXT,
        tags TEXT,
        custom_fields TEXT,
        loss_reason TEXT,
        loss_notes TEXT,
        zoho_deal_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    products: `
      CREATE TABLE products (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        sku TEXT UNIQUE,
        description TEXT,
        type TEXT DEFAULT 'service',
        unit_price REAL NOT NULL DEFAULT 0,
        currency TEXT DEFAULT 'AED',
        cost_price REAL,
        tax_rate REAL DEFAULT 5,
        track_inventory INTEGER DEFAULT 0,
        stock_quantity INTEGER DEFAULT 0,
        reorder_level INTEGER DEFAULT 10,
        unit TEXT DEFAULT 'pcs',
        tags TEXT,
        custom_fields TEXT,
        is_active INTEGER DEFAULT 1,
        zoho_item_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    quotes: `
      CREATE TABLE quotes (
        id TEXT PRIMARY KEY,
        quote_number TEXT NOT NULL UNIQUE,
        account_id TEXT,
        contact_id TEXT,
        opportunity_id TEXT,
        status TEXT NOT NULL,
        quote_date TEXT NOT NULL,
        valid_until TEXT,
        accepted_at TEXT,
        rejected_at TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        discount_amount REAL DEFAULT 0,
        discount_percent REAL DEFAULT 0,
        tax_amount REAL DEFAULT 0,
        total_amount REAL NOT NULL DEFAULT 0,
        currency TEXT DEFAULT 'AED',
        owner_id TEXT NOT NULL,
        team_id TEXT,
        subject TEXT,
        body TEXT,
        terms_conditions TEXT,
        notes TEXT,
        approved_by TEXT,
        approved_at TEXT,
        zoho_estimate_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    quote_line_items: `
      CREATE TABLE quote_line_items (
        id TEXT PRIMARY KEY,
        quote_id TEXT NOT NULL,
        product_id TEXT,
        line_number INTEGER NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        quantity REAL NOT NULL DEFAULT 1,
        unit TEXT DEFAULT 'pcs',
        unit_price REAL NOT NULL DEFAULT 0,
        discount_percent REAL DEFAULT 0,
        discount_amount REAL DEFAULT 0,
        tax_rate REAL DEFAULT 5,
        tax_amount REAL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        created_at TEXT,
        updated_at TEXT
      )
    `,
    sales_orders: `
      CREATE TABLE sales_orders (
        id TEXT PRIMARY KEY,
        order_number TEXT NOT NULL UNIQUE,
        quote_id TEXT,
        account_id TEXT,
        contact_id TEXT,
        opportunity_id TEXT,
        status TEXT NOT NULL,
        order_date TEXT NOT NULL,
        expected_ship_date TEXT,
        shipped_date TEXT,
        delivered_date TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        discount_amount REAL DEFAULT 0,
        discount_percent REAL DEFAULT 0,
        tax_amount REAL DEFAULT 0,
        total_amount REAL NOT NULL DEFAULT 0,
        currency TEXT DEFAULT 'AED',
        owner_id TEXT NOT NULL,
        team_id TEXT,
        shipping_address TEXT,
        billing_address TEXT,
        shipping_method TEXT,
        tracking_number TEXT,
        notes TEXT,
        internal_notes TEXT,
        zoho_salesorder_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    sales_order_line_items: `
      CREATE TABLE sales_order_line_items (
        id TEXT PRIMARY KEY,
        sales_order_id TEXT NOT NULL,
        product_id TEXT,
        line_number INTEGER NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        quantity REAL NOT NULL DEFAULT 1,
        unit TEXT DEFAULT 'pcs',
        unit_price REAL NOT NULL DEFAULT 0,
        discount_percent REAL DEFAULT 0,
        discount_amount REAL DEFAULT 0,
        tax_rate REAL DEFAULT 5,
        tax_amount REAL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        quantity_delivered REAL DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        created_at TEXT,
        updated_at TEXT
      )
    `,
    invoices: `
      CREATE TABLE invoices (
        id TEXT PRIMARY KEY,
        invoice_number TEXT NOT NULL UNIQUE,
        sales_order_id TEXT,
        quote_id TEXT,
        account_id TEXT,
        contact_id TEXT,
        status TEXT NOT NULL,
        invoice_date TEXT NOT NULL,
        due_date TEXT,
        sent_at TEXT,
        viewed_at TEXT,
        paid_at TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        discount_amount REAL DEFAULT 0,
        discount_percent REAL DEFAULT 0,
        tax_amount REAL DEFAULT 0,
        total_amount REAL NOT NULL DEFAULT 0,
        amount_paid REAL DEFAULT 0,
        amount_due REAL NOT NULL DEFAULT 0,
        currency TEXT DEFAULT 'AED',
        owner_id TEXT NOT NULL,
        team_id TEXT,
        billing_address TEXT,
        shipping_address TEXT,
        notes TEXT,
        terms_conditions TEXT,
        zoho_invoice_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
      )
    `,
    invoice_line_items: `
      CREATE TABLE invoice_line_items (
        id TEXT PRIMARY KEY,
        invoice_id TEXT NOT NULL,
        product_id TEXT,
        line_number INTEGER NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        quantity REAL NOT NULL DEFAULT 1,
        unit TEXT DEFAULT 'pcs',
        unit_price REAL NOT NULL DEFAULT 0,
        discount_percent REAL DEFAULT 0,
        discount_amount REAL DEFAULT 0,
        tax_rate REAL DEFAULT 5,
        tax_amount REAL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        created_at TEXT,
        updated_at TEXT
      )
    `,
    payments: `
      CREATE TABLE payments (
        id TEXT PRIMARY KEY,
        payment_number TEXT NOT NULL UNIQUE,
        invoice_id TEXT NOT NULL,
        amount REAL NOT NULL,
        currency TEXT DEFAULT 'AED',
        payment_date TEXT NOT NULL,
        payment_mode TEXT,
        reference_number TEXT,
        status TEXT DEFAULT 'completed',
        notes TEXT,
        zoho_payment_id TEXT,
        zoho_sync_status TEXT,
        zoho_last_synced_at TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT
      )
    `,
    activities: `
      CREATE TABLE activities (
        id TEXT PRIMARY KEY,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        type TEXT NOT NULL,
        subject TEXT NOT NULL,
        description TEXT,
        scheduled_at TEXT,
        due_at TEXT,
        completed_at TEXT,
        duration_minutes INTEGER,
        status TEXT NOT NULL,
        owner_id TEXT NOT NULL,
        assigned_to TEXT,
        outcome TEXT,
        created_by TEXT,
        created_at TEXT,
        updated_at TEXT
      )
    `,
    attachments: `
      CREATE TABLE attachments (
        id TEXT PRIMARY KEY,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        file_name TEXT NOT NULL,
        file_size INTEGER NOT NULL,
        mime_type TEXT NOT NULL,
        storage_path TEXT NOT NULL,
        public_url TEXT,
        uploaded_by TEXT,
        created_at TEXT
      )
    `,
  },

  tables: [
    "users",
    "teams",
    "accounts",
    "contacts",
    "leads",
    "opportunities",
    "products",
    "quotes",
    "quote_line_items",
    "sales_orders",
    "sales_order_line_items",
    "invoices",
    "invoice_line_items",
    "payments",
    "activities",
    "attachments",
  ],

  readOnlyTables: ["users", "teams", "products"],
  readWriteTables: [
    "leads", "contacts", "accounts", "opportunities",
    "quotes", "quote_line_items",
    "sales_orders", "sales_order_line_items",
    "invoices", "invoice_line_items",
    "payments", "activities", "attachments",
  ],

  syncInterval: 30000,
  batchSize: 100,

  retry: {
    maxRetries: 3,
    baseDelay: 1000,
    maxDelay: 30000,
  },
};

export function createPowerSyncClient() {
  return null;
}
